# Use a base image with necessary dependencies
FROM ubuntu:latest

ENV LANG en_US.UTF-8
ENV LC_ALL C.UTF-8
ENV DEBIAN_FRONTEND noninteractive

# Update package list and install required dependencies
RUN apt-get update && \
    apt-get install -y \
    git \
    gcc \
    make \
    libncurses5-dev \
    libatk1.0-dev \
    libcairo2-dev \
    python3-dev \
    ruby-dev \
    lua5.2 \
    liblua5.2-dev \
    libperl-dev \
    tcl-dev \
    curl \
    yamllint \
    pip \
    && rm -rf /var/lib/apt/lists/*

# Clone Vim source code
RUN git clone https://github.com/vim/vim.git /tmp/vim

# Change working directory to Vim source code
WORKDIR /tmp/vim

# Checkout Vim 8.1 version
#RUN git checkout master v8.1.0000

# Configure Vim build
RUN ./configure \
    --with-features=huge \
    --enable-multibyte \
    --enable-rubyinterp=yes \
    --enable-python3interp=yes \
    --with-python3-config-dir=/usr/lib/python3.8/config-3.8-x86_64-linux-gnu \
    --enable-perlinterp=yes \
    --enable-luainterp=yes \
    --enable-cscope \
    --prefix=/usr/local

# Compile and install Vim
RUN make && make install

RUN curl -fsSL https://deb.nodesource.com/setup_21.x | bash - && \
    apt-get install -y nodejs

RUN mkdir -p ~/.vim/pack/coc/start && \
    cd ~/.vim/pack/coc/start && \
    git clone --branch release https://github.com/neoclide/coc.nvim.git --depth=1 && \
    vim -c "helptags coc.nvim/doc/ | q" && \
    vim -c "CocInstall @yaegassy/coc-ansible | q"

RUN mkdir /vim

RUN pip3 install ansible-lint ansible

RUN mkdir ~/.vimrc
COPY init.vim ~/.vimrc/init.vim

# Cleanup
RUN rm -rf /tmp/vim \
    && apt-get purge -y \
    git \
    gcc \
    make \
    lua5.2 \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set entry point to Vim
ENTRYPOINT ["vim"]
