# Use a base image with necessary dependencies
FROM ubuntu:latest

# Update package list and install required dependencies
RUN apt-get update && \
    apt-get install -y \
    git \
    gcc \
    make \
    libncurses5-dev \
    libgtk2.0-dev \
    libatk1.0-dev \
    libcairo2-dev \
    libx11-dev \
    libxpm-dev \
    libxt-dev \
    python3-dev \
    ruby-dev \
    lua5.2 \
    liblua5.2-dev \
    libperl-dev \
    tcl-dev \
    && rm -rf /var/lib/apt/lists/*

# Clone Vim source code
RUN git clone https://github.com/vim/vim.git /tmp/vim

# Change working directory to Vim source code
WORKDIR /tmp/vim

# Checkout Vim 8.1 version
RUN git checkout v8.1.0000

# Configure Vim build
RUN ./configure \
    --with-features=huge \
    --enable-multibyte \
    --enable-rubyinterp=yes \
    --enable-python3interp=yes \
    --with-python3-config-dir=/usr/lib/python3.8/config-3.8-x86_64-linux-gnu \
    --enable-perlinterp=yes \
    --enable-luainterp=yes \
    --enable-gui=gtk2 \
    --enable-cscope \
    --prefix=/usr/local

# Compile and install Vim
RUN make && make install

# Cleanup
RUN rm -rf /tmp/vim \
    && apt-get purge -y \
    git \
    gcc \
    make \
    libncurses5-dev \
    libgtk2.0-dev \
    libatk1.0-dev \
    libcairo2-dev \
    libx11-dev \
    libxpm-dev \
    libxt-dev \
    python3-dev \
    ruby-dev \
    lua5.2 \
    liblua5.2-dev \
    libperl-dev \
    tcl-dev \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set entry point to Vim
ENTRYPOINT ["vim"]
